// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorigoApp.Persistence.Context;

#nullable disable

namespace WorigoApp.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241015231644_room-based-Transaction-add-new-column")]
    partial class roombasedTransactionaddnewcolumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorigoApp.Domain.Entites.CommentAndRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EmployeePoint")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("OrderItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("ProductPoint")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SpeedPoint")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("OrderItemId")
                        .IsUnique();

                    b.ToTable("CommentAndRatings");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Company");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(5528),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(5542),
                            Name = "Worigo"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(5545),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(5546),
                            Name = "Ramada"
                        });
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.ContentsOfFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.ToTable("ContentsOfFood");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(6727),
                            HotelId = 1,
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(6728),
                            Name = "Ön Büro Resepsiyon Departmanı"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(6731),
                            HotelId = 1,
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(6731),
                            Name = "Housekeeping Departmanı"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(6732),
                            HotelId = 1,
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(6732),
                            Name = "Yiyecek İçecek ve Mutfak Departmanı"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(6732),
                            HotelId = 1,
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(6733),
                            Name = "Teknik Servis Departmanı"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(6733),
                            HotelId = 1,
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(6734),
                            Name = "Sağlık Kulübü & Spa Departmanı"
                        });
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmployeeTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeTypeId");

                    b.HasIndex("HotelId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.EmployeeDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExitDateOfWork")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FloorNo")
                        .HasColumnType("int");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastOnlineTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("OnlineOrOfflineNow")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDateOfWork")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("EmployeeDetail");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.EmployeeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("HotelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("HotelId");

                    b.ToTable("EmployeeType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7899),
                            DepartmentId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7901),
                            Name = "Ön Büro Müdürü"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7903),
                            DepartmentId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7903),
                            Name = "Gece Müdürü"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7904),
                            DepartmentId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7904),
                            Name = "Ön Büro Şefi"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7905),
                            DepartmentId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7905),
                            Name = "Resepsiyonist"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7906),
                            DepartmentId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7906),
                            Name = "Concierge Şefi"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7906),
                            DepartmentId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7907),
                            Name = "Taşıyıcı/Karşılayıcı Personel"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7907),
                            DepartmentId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7907),
                            Name = "Guest Service Agent"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7908),
                            DepartmentId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7908),
                            Name = "Guest Relation"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7909),
                            DepartmentId = 2,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7909),
                            Name = "HK Müdürü"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7910),
                            DepartmentId = 2,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7910),
                            Name = "Housekeeper"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7910),
                            DepartmentId = 2,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7911),
                            Name = "Kat Şefi (Floor Supervisor)"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7911),
                            DepartmentId = 2,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7912),
                            Name = "Oda Görevlisi"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7912),
                            DepartmentId = 2,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7912),
                            Name = "Meydancı"
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7913),
                            DepartmentId = 3,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7913),
                            Name = "Yiyecek – İçecek Müdürü"
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7914),
                            DepartmentId = 3,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7914),
                            Name = "Barlar Şefi"
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7915),
                            DepartmentId = 3,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7915),
                            Name = "Bar Personeli"
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7915),
                            DepartmentId = 3,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7916),
                            Name = "Mutfak Şefi"
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7916),
                            DepartmentId = 3,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7916),
                            Name = "Mutfak Personeli"
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7917),
                            DepartmentId = 3,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7917),
                            Name = "Restoran Şefi"
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7918),
                            DepartmentId = 3,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7918),
                            Name = "Servis Personeli"
                        },
                        new
                        {
                            Id = 21,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7918),
                            DepartmentId = 4,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7919),
                            Name = "Teknik Müdür"
                        },
                        new
                        {
                            Id = 22,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7919),
                            DepartmentId = 4,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7920),
                            Name = "Elektrik Tekniker"
                        },
                        new
                        {
                            Id = 23,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7920),
                            DepartmentId = 4,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7920),
                            Name = "Mekanik Tekniker"
                        },
                        new
                        {
                            Id = 24,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7921),
                            DepartmentId = 4,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7921),
                            Name = "Tesisatçı"
                        },
                        new
                        {
                            Id = 25,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7922),
                            DepartmentId = 5,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(7922),
                            Name = "Masör"
                        });
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FoodMenuCategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FoodMenuCategoryId");

                    b.ToTable("Food");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.FoodMenuCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("FoodMenuCategory");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.FoodType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoomFoodTypeEnum")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FoodType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(8806),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(8808),
                            RoomFoodTypeEnum = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(8809),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(8809),
                            RoomFoodTypeEnum = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(8810),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(8810),
                            RoomFoodTypeEnum = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(8811),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(8811),
                            RoomFoodTypeEnum = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(8812),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(8812),
                            RoomFoodTypeEnum = 5
                        });
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.GServices.BellBoy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BellBoy");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(9603),
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 545, DateTimeKind.Local).AddTicks(9604),
                            Name = "Bagaj Taşıma"
                        });
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.GServices.Connection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FlootNo")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Connection");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(309),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(311),
                            Name = "1q2w3e4r5t"
                        });
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.GServices.DryCleaner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("DryCleaner");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.GServices.FeedBackAndSurvey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FeedBack")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("FeedBackAndSurveys");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.GServices.HotelInformationAndAnnouncements", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HotelInformationAndAnnouncements");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.GServices.HouseKeeping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HouseKeeping");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(3433),
                            ImageUrl = "",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(3436),
                            Name = "Havlu değişimi veya eksiği"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(3438),
                            ImageUrl = "",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(3438),
                            Name = "Oda Genel temizlik"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(3439),
                            ImageUrl = "",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(3439),
                            Name = "Çarşaf veya yatak yüzü değişimi"
                        });
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.GServices.SpaMassage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("SpaMassage");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(4108),
                            Description = "Uzak Doğu Masajı",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(4109),
                            Name = "Uzak Doğu",
                            Price = 200m
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(4111),
                            Description = "Tailand Masajı",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(4111),
                            Name = "Tailand Masajı",
                            Price = 200m
                        });
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.GServices.TechnicalNeed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TechnicalNeed");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(4923),
                            Description = "Klima ile arıza durumları",
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(4926),
                            Name = "Klima"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(4928),
                            Description = "TV ile arıza durumları",
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(4929),
                            Name = "TV"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(4929),
                            Description = "Minibar ile arıza durumları",
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(4929),
                            Name = "Minibar"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(4930),
                            Description = "Kapı ile arıza durumları",
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(4930),
                            Name = "Kapı"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(4931),
                            Description = "Elektirk ile arıza durumları",
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(4931),
                            Name = "Elektrik"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(4932),
                            Description = "Aydınlatma ile arıza durumları",
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(4932),
                            Name = "Aydınlatma"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(4933),
                            Description = "Aydınlatma ile arıza durumları",
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(4933),
                            Name = "Duş Ve Tuvalet"
                        });
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Companyid")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfStar")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Companyid");

                    b.ToTable("Hotel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adress = "Bağcılar",
                            Companyid = 2,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(5647),
                            Email = "tekstilkent@ramada.com",
                            IsActive = true,
                            IsDeleted = false,
                            Location = "Giyimkent",
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(5649),
                            Name = "Tekstilkent",
                            NumberOfStar = 4,
                            PhoneNumber = "02126733520"
                        });
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ImageCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ImageCategoryId");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.ImageCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("ImageCategory");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.LogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Exception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("LogEvent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageTemplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Logs", (string)null);
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoomBasedTransactionId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("RoomBasedTransactionId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("OrderStatusEnum")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ServiceItemId")
                        .HasColumnType("int");

                    b.Property<int>("ServicesEnumId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(9931),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(9934),
                            Name = "SystemAdmin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(9936),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(9936),
                            Name = "HotelAdmin"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(9937),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(9937),
                            Name = "Management"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(9937),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(9938),
                            Name = "DepartmentManager"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(9938),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(9939),
                            Name = "Employee"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(9939),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(9940),
                            Name = "Customer"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(9940),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 546, DateTimeKind.Local).AddTicks(9940),
                            Name = "Resepsiyonist"
                        });
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFull")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomFoodTypeId")
                        .HasColumnType("int");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("RoomFoodTypeId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.RoomBasedTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("VerificationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomBasedTransaction");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoomTypeEnum")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RoomType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 547, DateTimeKind.Local).AddTicks(685),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 547, DateTimeKind.Local).AddTicks(686),
                            RoomTypeEnum = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 547, DateTimeKind.Local).AddTicks(687),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 547, DateTimeKind.Local).AddTicks(687),
                            RoomTypeEnum = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 547, DateTimeKind.Local).AddTicks(688),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 547, DateTimeKind.Local).AddTicks(688),
                            RoomTypeEnum = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 547, DateTimeKind.Local).AddTicks(689),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 547, DateTimeKind.Local).AddTicks(689),
                            RoomTypeEnum = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 547, DateTimeKind.Local).AddTicks(690),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 547, DateTimeKind.Local).AddTicks(690),
                            RoomTypeEnum = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 547, DateTimeKind.Local).AddTicks(691),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 547, DateTimeKind.Local).AddTicks(691),
                            RoomTypeEnum = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 547, DateTimeKind.Local).AddTicks(692),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 547, DateTimeKind.Local).AddTicks(692),
                            RoomTypeEnum = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 547, DateTimeKind.Local).AddTicks(693),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 547, DateTimeKind.Local).AddTicks(693),
                            RoomTypeEnum = 8
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 547, DateTimeKind.Local).AddTicks(694),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 547, DateTimeKind.Local).AddTicks(694),
                            RoomTypeEnum = 9
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 547, DateTimeKind.Local).AddTicks(695),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 547, DateTimeKind.Local).AddTicks(695),
                            RoomTypeEnum = 10
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 547, DateTimeKind.Local).AddTicks(696),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 547, DateTimeKind.Local).AddTicks(696),
                            RoomTypeEnum = 11
                        });
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Translation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Translations");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 10, 16, 2, 16, 43, 547, DateTimeKind.Local).AddTicks(2019),
                            Email = "samt51.m@icloud.com",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 10, 16, 2, 16, 43, 547, DateTimeKind.Local).AddTicks(2021),
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.CommentAndRating", b =>
                {
                    b.HasOne("WorigoApp.Domain.Entites.Order", "Order")
                        .WithMany("CommentAndRatings")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorigoApp.Domain.Entites.OrderItem", "OrderItem")
                        .WithOne("CommentAndRating")
                        .HasForeignKey("WorigoApp.Domain.Entites.CommentAndRating", "OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.ContentsOfFood", b =>
                {
                    b.HasOne("WorigoApp.Domain.Entites.Food", "Food")
                        .WithMany("ContentsOfFoods")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Department", b =>
                {
                    b.HasOne("WorigoApp.Domain.Entites.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Employee", b =>
                {
                    b.HasOne("WorigoApp.Domain.Entites.EmployeeType", "EmployeeType")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeTypeId");

                    b.HasOne("WorigoApp.Domain.Entites.Hotel", "Hotel")
                        .WithMany("Employees")
                        .HasForeignKey("HotelId");

                    b.Navigation("EmployeeType");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.EmployeeDetail", b =>
                {
                    b.HasOne("WorigoApp.Domain.Entites.Employee", "Employee")
                        .WithOne("EmployeeDetail")
                        .HasForeignKey("WorigoApp.Domain.Entites.EmployeeDetail", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.EmployeeType", b =>
                {
                    b.HasOne("WorigoApp.Domain.Entites.Department", "Department")
                        .WithMany("EmployeeTypes")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorigoApp.Domain.Entites.Hotel", null)
                        .WithMany("Departments")
                        .HasForeignKey("HotelId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Food", b =>
                {
                    b.HasOne("WorigoApp.Domain.Entites.FoodMenuCategory", "FoodMenuCategory")
                        .WithMany("Foods")
                        .HasForeignKey("FoodMenuCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodMenuCategory");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.FoodMenuCategory", b =>
                {
                    b.HasOne("WorigoApp.Domain.Entites.Hotel", "Hotel")
                        .WithMany("FoodMenuCategories")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Hotel", b =>
                {
                    b.HasOne("WorigoApp.Domain.Entites.Company", "Company")
                        .WithMany("Hotels")
                        .HasForeignKey("Companyid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Image", b =>
                {
                    b.HasOne("WorigoApp.Domain.Entites.ImageCategory", "ImageCategory")
                        .WithMany("Images")
                        .HasForeignKey("ImageCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImageCategory");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.ImageCategory", b =>
                {
                    b.HasOne("WorigoApp.Domain.Entites.Hotel", "Hotel")
                        .WithMany("ImageCategories")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Order", b =>
                {
                    b.HasOne("WorigoApp.Domain.Entites.RoomBasedTransaction", "RoomBasedTransaction")
                        .WithMany("Orders")
                        .HasForeignKey("RoomBasedTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomBasedTransaction");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.OrderItem", b =>
                {
                    b.HasOne("WorigoApp.Domain.Entites.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Room", b =>
                {
                    b.HasOne("WorigoApp.Domain.Entites.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorigoApp.Domain.Entites.FoodType", "RoomFoodType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomFoodTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorigoApp.Domain.Entites.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("RoomFoodType");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.RoomBasedTransaction", b =>
                {
                    b.HasOne("WorigoApp.Domain.Entites.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Users", b =>
                {
                    b.HasOne("WorigoApp.Domain.Entites.Roles", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Company", b =>
                {
                    b.Navigation("Hotels");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Department", b =>
                {
                    b.Navigation("EmployeeTypes");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Employee", b =>
                {
                    b.Navigation("EmployeeDetail")
                        .IsRequired();
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.EmployeeType", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Food", b =>
                {
                    b.Navigation("ContentsOfFoods");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.FoodMenuCategory", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.FoodType", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Hotel", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Employees");

                    b.Navigation("FoodMenuCategories");

                    b.Navigation("ImageCategories");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.ImageCategory", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Order", b =>
                {
                    b.Navigation("CommentAndRatings");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.OrderItem", b =>
                {
                    b.Navigation("CommentAndRating")
                        .IsRequired();
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Roles", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.RoomBasedTransaction", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.RoomType", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
