// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorigoApp.Persistence.Context;

#nullable disable

namespace WorigoApp.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240506112145_add-serilog")]
    partial class addserilog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorigoApp.Domain.Entites.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Company");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(5792),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(5801),
                            Name = "Worigo"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(5803),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(5804),
                            Name = "Ramada"
                        });
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.ContentsOfFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.ToTable("ContentsOfFood");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(6834),
                            HotelId = 1,
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(6835),
                            Name = "Ön Büro Resepsiyon Departmanı"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(6837),
                            HotelId = 1,
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(6837),
                            Name = "Housekeeping Departmanı"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(6838),
                            HotelId = 1,
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(6838),
                            Name = "Yiyecek İçecek ve Mutfak Departmanı"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(6838),
                            HotelId = 1,
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(6839),
                            Name = "Teknik Servis Departmanı"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(6839),
                            HotelId = 1,
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(6839),
                            Name = "İnsan Kaynakları Departmanı"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(6840),
                            HotelId = 1,
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(6840),
                            Name = "Muhasebe Departmanı"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(6840),
                            HotelId = 1,
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(6841),
                            Name = "Satınalma Departmanı"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(6841),
                            HotelId = 1,
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(6841),
                            Name = "Satış ve Pazarlama Departmanı"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(6842),
                            HotelId = 1,
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(6842),
                            Name = "Bilgi İşlem Departmanı "
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(6842),
                            HotelId = 1,
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(6843),
                            Name = "Güvenlik Departmanı"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(6843),
                            HotelId = 1,
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(6843),
                            Name = "Sağlık Kulübü & Spa Departmanı"
                        });
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmployeeTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeTypeId");

                    b.HasIndex("HotelId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.EmployeeDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExitDateOfWork")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FloorNo")
                        .HasColumnType("int");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastOnlineTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("OnlineOrOfflineNow")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDateOfWork")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("EmployeeDetail");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.EmployeeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("EmployeeType");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FoodMenuCategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FoodMenuCategoryId");

                    b.ToTable("Food");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.FoodMenuCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("FoodMenuCategory");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.FoodType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoomFoodTypeEnum")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FoodType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(7476),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(7477),
                            RoomFoodTypeEnum = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(7477),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(7478),
                            RoomFoodTypeEnum = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(7478),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(7479),
                            RoomFoodTypeEnum = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(7479),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(7480),
                            RoomFoodTypeEnum = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(7480),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(7481),
                            RoomFoodTypeEnum = 5
                        });
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.GServices.BellBoy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BellBoy");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(7941),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(7941),
                            Name = "Bagaj Taşıma"
                        });
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.GServices.Connection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FlootNo")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Connection");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(8361),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(8362),
                            Name = "1q2w3e4r5t"
                        });
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.GServices.DryCleaner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DryCleaner");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.GServices.HotelInformationAndAnnouncements", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HotelInformationAndAnnouncements");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.GServices.HouseKeeping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HouseKeeping");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(8834),
                            ImageUrl = "",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(8834),
                            Name = "Havlu değişimi veya eksiği"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(8836),
                            ImageUrl = "",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(8836),
                            Name = "Oda Genel temizlik"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(8836),
                            ImageUrl = "",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(8837),
                            Name = "Çarşaf veya yatak yüzü değişimi"
                        });
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.GServices.SpaMassage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SpaMassage");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(9220),
                            Description = "Uzak Doğu Masajı",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(9220),
                            Name = "Uzak Doğu"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(9221),
                            Description = "Tailand Masajı",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(9222),
                            Name = "Tailand Masajı"
                        });
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.GServices.SpaMassageValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SpaMassageId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SpaMassageId");

                    b.ToTable("SpaMassageValue");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.GServices.TechnicalNeed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TechnicalNeed");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(9998),
                            Description = "Klima ile arıza durumları",
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 967, DateTimeKind.Local).AddTicks(9999),
                            Name = "Klima"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local),
                            Description = "TV ile arıza durumları",
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(1),
                            Name = "TV"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(1),
                            Description = "Minibar ile arıza durumları",
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(1),
                            Name = "Minibar"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(2),
                            Description = "Kapı ile arıza durumları",
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(2),
                            Name = "Kapı"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(3),
                            Description = "Elektirk ile arıza durumları",
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(3),
                            Name = "Elektrik"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(3),
                            Description = "Aydınlatma ile arıza durumları",
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(4),
                            Name = "Aydınlatma"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(4),
                            Description = "Aydınlatma ile arıza durumları",
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(4),
                            Name = "Duş Ve Tuvalet"
                        });
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Companyid")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfStar")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Companyid");

                    b.ToTable("Hotel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adress = "Bağcılar",
                            Companyid = 2,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(408),
                            Email = "tekstilkent@ramada.com",
                            IsActive = true,
                            IsDeleted = false,
                            Location = "Giyimkent",
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(409),
                            Name = "Tekstilkent",
                            NumberOfStar = 4,
                            PhoneNumber = "02126733520"
                        });
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ImageCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ImageCategoryId");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.ImageCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("ImageCategory");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.LogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Exception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("LogEvent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageTemplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Logs", (string)null);
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(3281),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(3285),
                            Name = "SystemAdmin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(3286),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(3286),
                            Name = "HotelAdmin"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(3287),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(3287),
                            Name = "Management"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(3287),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(3288),
                            Name = "DepartmentManager"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(3288),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(3288),
                            Name = "Employee"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(3289),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(3289),
                            Name = "Customer"
                        });
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomFoodTypeId")
                        .HasColumnType("int");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("RoomFoodTypeId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoomTypeEnum")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RoomType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(3806),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(3807),
                            RoomTypeEnum = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(3808),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(3808),
                            RoomTypeEnum = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(3809),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(3809),
                            RoomTypeEnum = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(3810),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(3810),
                            RoomTypeEnum = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(3811),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(3811),
                            RoomTypeEnum = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(3812),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(3812),
                            RoomTypeEnum = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(3813),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(3813),
                            RoomTypeEnum = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(3813),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(3814),
                            RoomTypeEnum = 8
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(3814),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(3815),
                            RoomTypeEnum = 9
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(3815),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(3815),
                            RoomTypeEnum = 10
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(3816),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 6, 14, 21, 44, 968, DateTimeKind.Local).AddTicks(3816),
                            RoomTypeEnum = 11
                        });
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.ContentsOfFood", b =>
                {
                    b.HasOne("WorigoApp.Domain.Entites.Food", "Food")
                        .WithMany("ContentsOfFoods")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Department", b =>
                {
                    b.HasOne("WorigoApp.Domain.Entites.Hotel", "Hotel")
                        .WithMany("Departments")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Employee", b =>
                {
                    b.HasOne("WorigoApp.Domain.Entites.EmployeeType", "EmployeeType")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeTypeId");

                    b.HasOne("WorigoApp.Domain.Entites.Hotel", "Hotel")
                        .WithMany("Employees")
                        .HasForeignKey("HotelId");

                    b.Navigation("EmployeeType");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.EmployeeDetail", b =>
                {
                    b.HasOne("WorigoApp.Domain.Entites.Employee", "Employee")
                        .WithOne("EmployeeDetail")
                        .HasForeignKey("WorigoApp.Domain.Entites.EmployeeDetail", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.EmployeeType", b =>
                {
                    b.HasOne("WorigoApp.Domain.Entites.Department", "Department")
                        .WithMany("EmployeeTypes")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Food", b =>
                {
                    b.HasOne("WorigoApp.Domain.Entites.FoodMenuCategory", "FoodMenuCategory")
                        .WithMany("Foods")
                        .HasForeignKey("FoodMenuCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodMenuCategory");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.FoodMenuCategory", b =>
                {
                    b.HasOne("WorigoApp.Domain.Entites.Hotel", "Hotel")
                        .WithMany("FoodMenuCategories")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.GServices.SpaMassageValue", b =>
                {
                    b.HasOne("WorigoApp.Domain.Entites.GServices.SpaMassage", "SpaMassage")
                        .WithMany("SpaMassageValues")
                        .HasForeignKey("SpaMassageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpaMassage");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Hotel", b =>
                {
                    b.HasOne("WorigoApp.Domain.Entites.Company", "Company")
                        .WithMany("Hotels")
                        .HasForeignKey("Companyid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Image", b =>
                {
                    b.HasOne("WorigoApp.Domain.Entites.ImageCategory", "ImageCategory")
                        .WithMany("Images")
                        .HasForeignKey("ImageCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImageCategory");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.ImageCategory", b =>
                {
                    b.HasOne("WorigoApp.Domain.Entites.Hotel", "Hotel")
                        .WithMany("ImageCategories")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Room", b =>
                {
                    b.HasOne("WorigoApp.Domain.Entites.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorigoApp.Domain.Entites.FoodType", "RoomFoodType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomFoodTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorigoApp.Domain.Entites.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("RoomFoodType");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Users", b =>
                {
                    b.HasOne("WorigoApp.Domain.Entites.Roles", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Company", b =>
                {
                    b.Navigation("Hotels");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Department", b =>
                {
                    b.Navigation("EmployeeTypes");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Employee", b =>
                {
                    b.Navigation("EmployeeDetail")
                        .IsRequired();
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.EmployeeType", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Food", b =>
                {
                    b.Navigation("ContentsOfFoods");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.FoodMenuCategory", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.FoodType", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.GServices.SpaMassage", b =>
                {
                    b.Navigation("SpaMassageValues");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Hotel", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Employees");

                    b.Navigation("FoodMenuCategories");

                    b.Navigation("ImageCategories");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.ImageCategory", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Roles", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.RoomType", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
