// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorigoApp.Persistence.Context;

#nullable disable

namespace WorigoApp.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240511140842_add-new-servi2")]
    partial class addnewservi2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorigoApp.Domain.Entites.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Company");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(5664),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(5674),
                            Name = "Worigo"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(5677),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(5677),
                            Name = "Ramada"
                        });
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.ContentsOfFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.ToTable("ContentsOfFood");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(6494),
                            HotelId = 1,
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(6496),
                            Name = "Ön Büro Resepsiyon Departmanı"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(6498),
                            HotelId = 1,
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(6498),
                            Name = "Housekeeping Departmanı"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(6498),
                            HotelId = 1,
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(6499),
                            Name = "Yiyecek İçecek ve Mutfak Departmanı"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(6499),
                            HotelId = 1,
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(6499),
                            Name = "Teknik Servis Departmanı"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(6500),
                            HotelId = 1,
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(6500),
                            Name = "Sağlık Kulübü & Spa Departmanı"
                        });
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmployeeTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeTypeId");

                    b.HasIndex("HotelId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.EmployeeDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExitDateOfWork")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FloorNo")
                        .HasColumnType("int");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastOnlineTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("OnlineOrOfflineNow")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDateOfWork")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("EmployeeDetail");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.EmployeeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("HotelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("HotelId");

                    b.ToTable("EmployeeType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7071),
                            DepartmentId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7071),
                            Name = "Ön Büro Müdürü"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7072),
                            DepartmentId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7073),
                            Name = "Gece Müdürü"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7073),
                            DepartmentId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7073),
                            Name = "Ön Büro Şefi"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7074),
                            DepartmentId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7074),
                            Name = "Resepsiyonist"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7075),
                            DepartmentId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7075),
                            Name = "Concierge Şefi"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7075),
                            DepartmentId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7075),
                            Name = "Taşıyıcı/Karşılayıcı Personel"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7076),
                            DepartmentId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7076),
                            Name = "Guest Service Agent"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7076),
                            DepartmentId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7077),
                            Name = "Guest Relation"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7077),
                            DepartmentId = 2,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7077),
                            Name = "HK Müdürü"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7078),
                            DepartmentId = 2,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7078),
                            Name = "Housekeeper"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7078),
                            DepartmentId = 2,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7079),
                            Name = "Kat Şefi (Floor Supervisor)"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7079),
                            DepartmentId = 2,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7079),
                            Name = "Oda Görevlisi"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7079),
                            DepartmentId = 2,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7080),
                            Name = "Meydancı"
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7080),
                            DepartmentId = 3,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7080),
                            Name = "Yiyecek – İçecek Müdürü"
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7081),
                            DepartmentId = 3,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7081),
                            Name = "Barlar Şefi"
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7081),
                            DepartmentId = 3,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7081),
                            Name = "Bar Personeli"
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7082),
                            DepartmentId = 3,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7082),
                            Name = "Mutfak Şefi"
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7082),
                            DepartmentId = 3,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7083),
                            Name = "Mutfak Personeli"
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7083),
                            DepartmentId = 3,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7083),
                            Name = "Restoran Şefi"
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7083),
                            DepartmentId = 3,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7084),
                            Name = "Servis Personeli"
                        },
                        new
                        {
                            Id = 21,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7084),
                            DepartmentId = 4,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7084),
                            Name = "Teknik Müdür"
                        },
                        new
                        {
                            Id = 22,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7085),
                            DepartmentId = 4,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7085),
                            Name = "Elektrik Tekniker"
                        },
                        new
                        {
                            Id = 23,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7085),
                            DepartmentId = 4,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7085),
                            Name = "Mekanik Tekniker"
                        },
                        new
                        {
                            Id = 24,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7086),
                            DepartmentId = 4,
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7086),
                            Name = "Tesisatçı"
                        });
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FoodMenuCategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FoodMenuCategoryId");

                    b.ToTable("Food");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.FoodMenuCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("FoodMenuCategory");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.FoodType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoomFoodTypeEnum")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FoodType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7520),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7520),
                            RoomFoodTypeEnum = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7521),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7521),
                            RoomFoodTypeEnum = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7522),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7522),
                            RoomFoodTypeEnum = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7523),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7523),
                            RoomFoodTypeEnum = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7524),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7524),
                            RoomFoodTypeEnum = 5
                        });
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.GServices.BellBoy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BellBoy");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7876),
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(7877),
                            Name = "Bagaj Taşıma"
                        });
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.GServices.Connection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FlootNo")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Connection");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(8286),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(8286),
                            Name = "1q2w3e4r5t"
                        });
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.GServices.DryCleaner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("DryCleaner");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.GServices.FeedBackAndSurvey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FeedBack")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("FeedBackAndSurveys");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.GServices.HotelInformationAndAnnouncements", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HotelInformationAndAnnouncements");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.GServices.HouseKeeping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HouseKeeping");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(9581),
                            ImageUrl = "",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(9582),
                            Name = "Havlu değişimi veya eksiği"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(9583),
                            ImageUrl = "",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(9584),
                            Name = "Oda Genel temizlik"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(9584),
                            ImageUrl = "",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(9584),
                            Name = "Çarşaf veya yatak yüzü değişimi"
                        });
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.GServices.SpaMassage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("SpaMassage");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(9988),
                            Description = "Uzak Doğu Masajı",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(9988),
                            Name = "Uzak Doğu",
                            Price = 0m
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(9990),
                            Description = "Tailand Masajı",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 976, DateTimeKind.Local).AddTicks(9991),
                            Name = "Tailand Masajı",
                            Price = 0m
                        });
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.GServices.TechnicalNeed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TechnicalNeed");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(309),
                            Description = "Klima ile arıza durumları",
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(310),
                            Name = "Klima"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(312),
                            Description = "TV ile arıza durumları",
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(312),
                            Name = "TV"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(312),
                            Description = "Minibar ile arıza durumları",
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(313),
                            Name = "Minibar"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(341),
                            Description = "Kapı ile arıza durumları",
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(341),
                            Name = "Kapı"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(341),
                            Description = "Elektirk ile arıza durumları",
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(342),
                            Name = "Elektrik"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(342),
                            Description = "Aydınlatma ile arıza durumları",
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(342),
                            Name = "Aydınlatma"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(343),
                            Description = "Aydınlatma ile arıza durumları",
                            ImageUrl = "1.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(343),
                            Name = "Duş Ve Tuvalet"
                        });
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Companyid")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfStar")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Companyid");

                    b.ToTable("Hotel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adress = "Bağcılar",
                            Companyid = 2,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(685),
                            Email = "tekstilkent@ramada.com",
                            IsActive = true,
                            IsDeleted = false,
                            Location = "Giyimkent",
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(686),
                            Name = "Tekstilkent",
                            NumberOfStar = 4,
                            PhoneNumber = "02126733520"
                        });
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ImageCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ImageCategoryId");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.ImageCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("ImageCategory");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.LogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Exception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("LogEvent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageTemplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Logs", (string)null);
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(3240),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(3249),
                            Name = "SystemAdmin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(3252),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(3252),
                            Name = "HotelAdmin"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(3253),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(3253),
                            Name = "Management"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(3254),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(3254),
                            Name = "DepartmentManager"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(3254),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(3255),
                            Name = "Employee"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(3291),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(3292),
                            Name = "Customer"
                        });
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomFoodTypeId")
                        .HasColumnType("int");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("RoomFoodTypeId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoomTypeEnum")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RoomType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(3873),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(3874),
                            RoomTypeEnum = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(3875),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(3876),
                            RoomTypeEnum = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(3876),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(3876),
                            RoomTypeEnum = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(3877),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(3877),
                            RoomTypeEnum = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(3878),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(3878),
                            RoomTypeEnum = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(3879),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(3879),
                            RoomTypeEnum = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(3879),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(3880),
                            RoomTypeEnum = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(3880),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(3880),
                            RoomTypeEnum = 8
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(3881),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(3881),
                            RoomTypeEnum = 9
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(3881),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(3882),
                            RoomTypeEnum = 10
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(3882),
                            IsActive = true,
                            IsDeleted = false,
                            ModifyDate = new DateTime(2024, 5, 11, 17, 8, 41, 977, DateTimeKind.Local).AddTicks(3883),
                            RoomTypeEnum = 11
                        });
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.ContentsOfFood", b =>
                {
                    b.HasOne("WorigoApp.Domain.Entites.Food", "Food")
                        .WithMany("ContentsOfFoods")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Department", b =>
                {
                    b.HasOne("WorigoApp.Domain.Entites.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Employee", b =>
                {
                    b.HasOne("WorigoApp.Domain.Entites.EmployeeType", "EmployeeType")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeTypeId");

                    b.HasOne("WorigoApp.Domain.Entites.Hotel", "Hotel")
                        .WithMany("Employees")
                        .HasForeignKey("HotelId");

                    b.Navigation("EmployeeType");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.EmployeeDetail", b =>
                {
                    b.HasOne("WorigoApp.Domain.Entites.Employee", "Employee")
                        .WithOne("EmployeeDetail")
                        .HasForeignKey("WorigoApp.Domain.Entites.EmployeeDetail", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.EmployeeType", b =>
                {
                    b.HasOne("WorigoApp.Domain.Entites.Department", "Department")
                        .WithMany("EmployeeTypes")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorigoApp.Domain.Entites.Hotel", null)
                        .WithMany("Departments")
                        .HasForeignKey("HotelId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Food", b =>
                {
                    b.HasOne("WorigoApp.Domain.Entites.FoodMenuCategory", "FoodMenuCategory")
                        .WithMany("Foods")
                        .HasForeignKey("FoodMenuCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodMenuCategory");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.FoodMenuCategory", b =>
                {
                    b.HasOne("WorigoApp.Domain.Entites.Hotel", "Hotel")
                        .WithMany("FoodMenuCategories")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Hotel", b =>
                {
                    b.HasOne("WorigoApp.Domain.Entites.Company", "Company")
                        .WithMany("Hotels")
                        .HasForeignKey("Companyid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Image", b =>
                {
                    b.HasOne("WorigoApp.Domain.Entites.ImageCategory", "ImageCategory")
                        .WithMany("Images")
                        .HasForeignKey("ImageCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImageCategory");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.ImageCategory", b =>
                {
                    b.HasOne("WorigoApp.Domain.Entites.Hotel", "Hotel")
                        .WithMany("ImageCategories")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Room", b =>
                {
                    b.HasOne("WorigoApp.Domain.Entites.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorigoApp.Domain.Entites.FoodType", "RoomFoodType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomFoodTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorigoApp.Domain.Entites.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("RoomFoodType");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Users", b =>
                {
                    b.HasOne("WorigoApp.Domain.Entites.Roles", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Company", b =>
                {
                    b.Navigation("Hotels");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Department", b =>
                {
                    b.Navigation("EmployeeTypes");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Employee", b =>
                {
                    b.Navigation("EmployeeDetail")
                        .IsRequired();
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.EmployeeType", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Food", b =>
                {
                    b.Navigation("ContentsOfFoods");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.FoodMenuCategory", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.FoodType", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Hotel", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Employees");

                    b.Navigation("FoodMenuCategories");

                    b.Navigation("ImageCategories");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.ImageCategory", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.Roles", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("WorigoApp.Domain.Entites.RoomType", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
